name: Build-Test
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Verify folder structure
      run: |
        echo "Building project..."
        ls -R
